import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { CheckCircle2, Phone } from 'lucide-react';

const siteUrl = 'https://www.sriselvamurugan.com';
const phone = '+919962675329';
const whatsapp = 'https://wa.me/919962675329?text=Hello%20Sri%20Selvamurugan%20Transport,%20I%20would%20like%20to%20request%20a%20quote.';

const pages = {
  'm-sand': { name: 'M-Sand', route: 'm-sand', image: '/images/m-sand.jpg', title: 'M-Sand Supplier | Chennai, Chengalpattu & Nearby Areas', description: 'M-Sand for concrete, block work and construction projects, with lorry delivery across Chennai, Tambaram, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu.', intro: 'M-Sand, or manufactured sand, is a finely processed aggregate used in concrete and masonry applications. Tell us about your project and delivery location so we can help you enquire about supply and transport.', uses: ['Concrete and RCC work', 'Block work and masonry', 'Residential and commercial construction'], areas: 'M-Sand delivery can be arranged for Chennai, Tambaram, Pallavaram, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu. Availability depends on the site location and material requirement.', imageAlt: 'M-Sand stock for construction material delivery', faqs: [['What is M-Sand used for?', 'M-Sand is commonly used for concrete, masonry and block work. The right material and quantity depend on the work being carried out.'], ['Can you deliver M-Sand to my site?', 'Share your location and required quantity so we can confirm M-Sand supply and lorry delivery options.']] },
  'river-sand': { name: 'River Sand', route: 'river-sand', image: '/images/riversand.jpg', title: 'River Sand Supplier | Chennai, Chengalpattu & Nearby Areas', description: 'Enquire about River Sand supply and lorry delivery for masonry, concrete and plastering projects in Chennai, Chengalpattu, Thiruporur and nearby areas.', intro: 'River Sand is used for a range of construction tasks, including masonry, concrete and fine plastering work. We make it simple to enquire about available River Sand and transport to your construction site.', uses: ['Masonry and brickwork', 'Concrete work', 'Fine plastering applications'], areas: 'For River Sand requirements, we serve sites across Chennai and the southern corridor through OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu. Contact us to check delivery for your site.', imageAlt: 'River sand ready for construction delivery', faqs: [['What projects use River Sand?', 'River Sand may be used in masonry, concrete and plastering work. Discuss your application with your engineer or contractor before ordering.'], ['How do I order River Sand?', 'Call or WhatsApp with the required material, approximate quantity and delivery location to check supply and delivery options.']] },
  'stone-jalli': { name: 'Stone Jalli / Blue Metal', route: 'stone-jalli', image: '/images/stone-jalli.jpg', title: 'Stone Jalli & Blue Metal Supplier | Chennai & Chengalpattu', description: 'Stone Jalli and Blue Metal for concrete, foundations and site work, with delivery across Chennai, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu.', intro: 'Stone Jalli, also called Blue Metal, is crushed stone aggregate used where a stable base or concrete mix is needed. We help arrange aggregate supply and lorry transport for building and site-development requirements.', uses: ['Concrete mixtures', 'Foundations and base preparation', 'Road and site-development work'], areas: 'Stone Jalli delivery is available across Chennai, Tambaram, Sholinganallur, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu, subject to the delivery location and requirement.', imageAlt: 'Stone jalli blue metal aggregate for construction', faqs: [['Is Stone Jalli the same as Blue Metal?', 'Stone Jalli is commonly referred to as Blue Metal or crushed stone aggregate.'], ['Where do you deliver Stone Jalli?', 'Tell us your site location and application so we can discuss material supply and lorry delivery.']] },
  'filling-gravel': { name: 'Filling Gravel', route: 'filling-gravel', image: '/images/filling-gravel.jpg', title: 'Filling Gravel Supplier | Chennai, Chengalpattu & Nearby Areas', description: 'Filling Gravel for levelling, drainage and site preparation, with lorry delivery for Chennai, Tambaram, Kelambakkam, Thiruporur and Chengalpattu sites.', intro: 'Filling Gravel supports site preparation before construction begins. It can be used for filling, levelling and drainage preparation, depending on the site plan. We supply filling material and coordinate lorry delivery to your location.', uses: ['Site filling and levelling', 'Drainage preparation', 'Pre-construction ground preparation'], areas: 'For filling and levelling requirements, delivery can be discussed for Chennai, Tambaram, Vandalur, Guduvanchery, Kelambakkam, Thiruporur and Chengalpattu.', imageAlt: 'Filling gravel for site levelling and preparation', faqs: [['What is Filling Gravel used for?', 'Filling Gravel is generally used for site filling, levelling and drainage preparation.'], ['Can Filling Gravel be delivered by lorry?', 'Yes. Share your site location and approximate requirement to discuss availability and delivery.']] },
  'red-sand': { name: 'Red Sand', route: 'red-sand', image: '/images/red-sand.jpg', title: 'Red Sand Supplier | Chennai, Chengalpattu & Nearby Areas', description: 'Enquire about Red Sand for filling, landscaping and selected construction requirements, with lorry delivery across Chennai and nearby service areas.', intro: 'Red Sand can be considered for filling, landscaping and selected construction requirements. Share the intended use, approximate quantity and site location to discuss material availability and delivery.', uses: ['Filling requirements', 'Landscaping work', 'Selected site-development applications'], areas: 'We can discuss Red Sand delivery for construction sites in Chennai, Medavakkam, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu.', imageAlt: 'Red sand for filling and landscaping work', faqs: [['What is Red Sand used for?', 'Red Sand may be used for filling, landscaping and selected site requirements. Check the right material with your contractor or engineer.'], ['How can I request Red Sand?', 'Call or WhatsApp with your requirement, quantity and delivery location for a supply enquiry.']] },
  'jcb-lorry-services': { name: 'JCB & Lorry Services', route: 'jcb-lorry-services', image: '/images/jcb.jpg', title: 'JCB & Lorry Services | Chennai, Chengalpattu & Nearby Areas', description: 'JCB earthwork and lorry transport for construction sites across Chennai, Chengalpattu, Thiruporur, Kelambakkam, OMR and ECR.', intro: 'Construction projects need dependable machinery and transport as well as the right materials. Our JCB and lorry services support site clearing, levelling, excavation, loading and construction-material delivery.', uses: ['Site clearing, levelling and excavation', 'Material loading and unloading', 'Construction-material lorry delivery'], areas: 'JCB and lorry support can be arranged across Chennai, Tambaram, OMR, ECR, Kelambakkam, Thiruporur and Chengalpattu. Share your site requirement to confirm availability.', imageAlt: 'JCB earthwork equipment at a construction site', faqs: [['What JCB work do you support?', 'We support site clearing, levelling, foundation excavation, trenching and material handling.'], ['Can you deliver construction materials by lorry?', 'Yes. Share the material, quantity and site location to discuss lorry transport.']] }
};

export default function MaterialLanding({ pageKey }) {
  const page = pages[pageKey];
  const canonical = `${siteUrl}/${page.route}`;
  const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Service', name: page.name, serviceType: page.name, description: page.intro, image: `${siteUrl}${page.image}`, url: canonical, provider: { '@id': `${siteUrl}/#business` } }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: page.name, item: canonical }] }] };
  const parent = page.route === 'jcb-lorry-services' ? '/services' : '/materials';
  const parentName = page.route === 'jcb-lorry-services' ? 'Services' : 'Materials';
  return <div className="py-12 sm:py-20 bg-slate-50 dark:bg-slate-950 min-h-screen transition-colors duration-300">
    <Helmet><title>{page.title}</title><meta name="description" content={page.description} /><link rel="canonical" href={canonical} /><meta property="og:title" content={page.title} /><meta property="og:description" content={page.description} /><meta property="og:url" content={canonical} /><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
      <nav aria-label="Breadcrumb" className="text-sm text-slate-500 dark:text-slate-400 mb-8"><Link to="/" className="hover:text-brand-500">Home</Link> <span aria-hidden="true">/</span> <Link to={parent} className="hover:text-brand-500">{parentName}</Link> <span aria-hidden="true">/</span> <span>{page.name}</span></nav>
      <div className="grid lg:grid-cols-2 gap-10 lg:gap-16 items-center"><div><h1 className="text-3xl sm:text-4xl md:text-5xl font-display font-bold text-brand-dark dark:text-white leading-tight">{page.name} for Chennai, Chengalpattu & Nearby Areas</h1><p className="mt-6 text-base sm:text-lg text-slate-600 dark:text-slate-300 leading-relaxed">{page.intro}</p><h2 className="mt-8 text-2xl font-display font-bold text-brand-dark dark:text-white">Common applications</h2><ul className="mt-4 space-y-3">{page.uses.map(use => <li key={use} className="flex gap-3 text-slate-600 dark:text-slate-300"><CheckCircle2 className="text-brand-500 shrink-0" size={20} />{use}</li>)}</ul><div className="mt-8 flex flex-col sm:flex-row gap-3"><a href={`tel:${phone}`} className="bg-brand-500 hover:bg-brand-600 text-white px-6 py-3.5 rounded-xl font-medium text-center inline-flex justify-center items-center gap-2"><Phone size={18} />Call for a Quote</a><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="border border-brand-500 text-brand-600 dark:text-brand-400 px-6 py-3.5 rounded-xl font-medium text-center">WhatsApp Us</a></div></div><img src={page.image} alt={page.imageAlt} width="1080" height="1512" className="w-full max-h-[520px] object-cover rounded-3xl shadow-xl" /></div>
      <section className="mt-16 sm:mt-24 max-w-4xl"><h2 className="text-2xl sm:text-3xl font-display font-bold text-brand-dark dark:text-white">Supply and delivery areas</h2><p className="mt-4 text-slate-600 dark:text-slate-300 leading-relaxed">{page.areas}</p><Link to="/areas-we-serve" className="inline-block mt-4 text-brand-600 dark:text-brand-400 font-semibold hover:underline">View all areas we serve &rarr;</Link></section>
      <section className="mt-14 sm:mt-20 max-w-4xl"><h2 className="text-2xl sm:text-3xl font-display font-bold text-brand-dark dark:text-white">{page.name} FAQs</h2><div className="mt-6 space-y-4">{page.faqs.map(([question, answer]) => <details key={question} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5"><summary className="font-semibold cursor-pointer text-brand-dark dark:text-white">{question}</summary><p className="mt-3 text-slate-600 dark:text-slate-300 leading-relaxed">{answer}</p></details>)}</div></section>
      <section className="mt-14 bg-white dark:bg-slate-900 rounded-2xl p-6 sm:p-8 border border-slate-200 dark:border-slate-800"><h2 className="text-2xl font-display font-bold text-brand-dark dark:text-white">Need {page.name} for your project?</h2><p className="mt-3 text-slate-600 dark:text-slate-300">Tell us your material requirement, approximate quantity and delivery location. We will help you enquire about supply and lorry delivery.</p><Link to="/contact" className="inline-block mt-5 bg-brand-500 hover:bg-brand-600 text-white px-6 py-3 rounded-xl font-medium">Request a Quote</Link></section>
    </div>
  </div>;
}
